version = "v2"

description = "Coder"
display_name = "Coder is a Cloud Development Environment platform that enables developers to work securely and efficiently from anywhere."
readme       = "./readme.md"
