name              = "certificate"
type              = "terraform_module"
terraform_version = "1.11.3"

[public_repo]
repo      = "nuonco/components"
directory = "aws/certificate"
branch    = "main"

[vars]
zone_id     = "{{ .nuon.install.sandbox.outputs.nuon_dns.public_domain.zone_id }}"
domain_name = "{{ .nuon.install.sandbox.outputs.nuon_dns.public_domain.name }}"
